
import "../../public/styles/theme.min.css";
import { UserContextProvider } from "../app/Context/userContext";
import { TeacherContextProvider } from "../app/Context/teacherContext";
import { RouteGuardContextProvider } from "../app/Context/RouteGuardContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-sky-500">
        <main>
          <RouteGuardContextProvider>
            <UserContextProvider>
              <TeacherContextProvider>
                {children}
              </TeacherContextProvider>
            </UserContextProvider>
          </RouteGuardContextProvider>
        </main>
      </body>
    </html>
  );
}
